#iris_classification

딥러닝 프레임 워크중 하나인 Tensorflow로 iris 분류 모델을 만들어보겠습니다.



##data_load

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()

In [ ]:
# feature
print(iris.data)
print(iris.feature_names)

# label
print(iris.target)
print(iris.target_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

##data_split

In [ ]:
import tensorflow as tf
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

iris_label = to_categorical(iris.target)

X = iris.data
y = iris_label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 3)
(30, 3)


##Sequential API

input으로는 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']이 들어갑니다.

따라서 shape이 4이고 output은 ['setosa' 'versicolor' 'virginica'] 중 하나의 종류가 출력되므로 3입니다.

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
from keras.optimizers import Adam

model = keras.models.Sequential([
      layers.Dense(128, input_dim = 4, activation='relu'),
      layers.Dense(64, activation='relu'),
      layers.Dense(32, activation='relu'),
      layers.Dense(3, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               640       
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 3)                 99        
                                                                 
Total params: 11,075
Trainable params: 11,075
Non-trainable params: 0
_________________________________________________________________


##Functional API

In [ ]:
inputs = keras.Input(shape = (4,))
x = layers.Dense(128, activation='relu')(inputs)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dense(32, activation='relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)

model = keras.Model(inputs=inputs, outputs=outputs)


model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model.summary()

Model: "model_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_29 (Dense)            (None, 128)               640       
                                                                 
 dense_30 (Dense)            (None, 64)                8256      
                                                                 
 dense_31 (Dense)            (None, 32)                2080      
                                                                 
 dense_32 (Dense)            (None, 3)                 99        
                                                                 
Total params: 11,075
Trainable params: 11,075
Non-trainable params: 0
_________________________________________________________________


##Subclassing API

In [ ]:
class model(tf.keras.Model):
  def __init__(self):
    super(model, self).__init__()
    self.dense1 = layers.Dense(128, activation='relu')
    self.dense2 = layers.Dense(64, activation='relu')
    self.dense3 = layers.Dense(32, activation='relu')
    self.dense4 = layers.Dense(3, activation='softmax')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    x = self.dense3(x)
    x = self.dense4(x)
    return x

model = model()
model.build(input_shape=(1,4))

In [ ]:
model.summary()

Model: "model_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_41 (Dense)            multiple                  640       
                                                                 
 dense_42 (Dense)            multiple                  8256      
                                                                 
 dense_43 (Dense)            multiple                  2080      
                                                                 
 dense_44 (Dense)            multiple                  99        
                                                                 
Total params: 11,075
Trainable params: 11,075
Non-trainable params: 0
_________________________________________________________________


##model_train

In [ ]:
hist = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 60ms/step - loss: 1.1427 - accuracy: 0.3667 - val_loss: 0.9576 - val_accuracy: 0.5667
Epoch 2/10
4/4 [==============================] - 0s 10ms/step - loss: 0.9447 - accuracy: 0.6583 - val_loss: 0.8885 - val_accuracy: 0.6333
Epoch 3/10
4/4 [==============================] - 0s 15ms/step - loss: 0.8561 - accuracy: 0.6667 - val_loss: 0.8072 - val_accuracy: 0.6667
Epoch 4/10
4/4 [==============================] - 0s 10ms/step - loss: 0.7811 - accuracy: 0.6667 - val_loss: 0.7361 - val_accuracy: 0.6667
Epoch 5/10
4/4 [==============================] - 0s 10ms/step - loss: 0.7030 - accuracy: 0.7167 - val_loss: 0.6518 - val_accuracy: 0.8333
Epoch 6/10
4/4 [==============================] - 0s 9ms/step - loss: 0.6266 - accuracy: 0.7917 - val_loss: 0.5816 - val_accuracy: 0.8667
Epoch 7/10
4/4 [==============================] - 0s 9ms/step - loss: 0.5673 - accuracy: 0.7833 - val_loss: 0.5303 - val_accuracy: 0.7667
Epoch 8/10
4/4 [=============

##model_result

In [ ]:
import numpy as np
from sklearn.metrics import classification_report,confusion_matrix

y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

1/1 [==============================] - 0s 14ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.80      0.89        10
           2       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

[[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]
