##Wine(Tensorflow)



###Wine 데이터 로드

In [ ]:
from sklearn.datasets import load_wine

wine = load_wine()

---

###데이터 확인

In [ ]:
# feature
print(wine.data)
print(wine.feature_names)

# label
print(wine.target)
print(wine.target_names)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
['class_0' 'class_1'

---

###데이터 분리

In [ ]:
import tensorflow as tf
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

wine_label = to_categorical(wine.target)

X = wine.data
y = wine_label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(142, 13)
(36, 13)
(142, 3)
(36, 3)


---

###Sequential API

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
from keras.optimizers import Adam

model1 = keras.models.Sequential([
      layers.Dense(512, input_dim = 13, activation='relu'),
      layers.Dense(256, activation='relu'),
      layers.Dense(128, activation='relu'),
      layers.Dense(64, activation='relu'),
      layers.Dense(32, activation='relu'),
      layers.Dense(3, activation='softmax')
])

model1.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               7168      
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 64)                8256      
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 3)                 99        
                                                                 
Total params: 181,827
Trainable params: 181,827
Non-trai

----

###Functional API

In [ ]:
inputs = keras.Input(shape = (13,))
x = layers.Dense(512, activation='relu')(inputs)
x = layers.Dense(256, activation='relu')(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dense(32, activation='relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)

model2 = keras.Model(inputs=inputs, outputs=outputs)

model2.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model2.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_6 (Dense)             (None, 512)               7168      
                                                                 
 dense_7 (Dense)             (None, 256)               131328    
                                                                 
 dense_8 (Dense)             (None, 128)               32896     
                                                                 
 dense_9 (Dense)             (None, 64)                8256      
                                                                 
 dense_10 (Dense)            (None, 32)                2080      
                                                                 
 dense_11 (Dense)            (None, 3)                 99    

---

###Subclassing API

In [ ]:
class model(tf.keras.Model):
  def __init__(self):
    super(model, self).__init__()
    self.dense1 = layers.Dense(512, activation='relu')
    self.dense2 = layers.Dense(256, activation='relu')
    self.dense3 = layers.Dense(128, activation='relu')
    self.dense4 = layers.Dense(64, activation='relu')
    self.dense5 = layers.Dense(32, activation='relu')
    self.dense6 = layers.Dense(3, activation='softmax')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    x = self.dense3(x)
    x = self.dense4(x)
    x = self.dense5(x)
    x = self.dense6(x)
    return X

model3 = model()
model3.build(input_shape=(1, 13))
model3.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model3.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_30 (Dense)            multiple                  7168      
                                                                 
 dense_31 (Dense)            multiple                  131328    
                                                                 
 dense_32 (Dense)            multiple                  32896     
                                                                 
 dense_33 (Dense)            multiple                  8256      
                                                                 
 dense_34 (Dense)            multiple                  2080      
                                                                 
 dense_35 (Dense)            multiple                  99        
                                                                 
Total params: 181,827
Trainable params: 181,827
Non-trainab

---

###Model 학습

Subclassing API방식으로 만든 모델은 학습 도중 오류가 발생하였습니다.(추후 수정 예정)

In [ ]:
hist = model1.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 64ms/step - loss: 14.5206 - accuracy: 0.3944 - val_loss: 3.7017 - val_accuracy: 0.2778
Epoch 2/10
5/5 [==============================] - 0s 13ms/step - loss: 2.4833 - accuracy: 0.3803 - val_loss: 1.0490 - val_accuracy: 0.5278
Epoch 3/10
5/5 [==============================] - 0s 11ms/step - loss: 1.1858 - accuracy: 0.3944 - val_loss: 1.9509 - val_accuracy: 0.3889
Epoch 4/10
5/5 [==============================] - 0s 12ms/step - loss: 1.2325 - accuracy: 0.5282 - val_loss: 0.8347 - val_accuracy: 0.4722
Epoch 5/10
5/5 [==============================] - 0s 16ms/step - loss: 1.5071 - accuracy: 0.4577 - val_loss: 1.6488 - val_accuracy: 0.3056
Epoch 6/10
5/5 [==============================] - 0s 11ms/step - loss: 1.1312 - accuracy: 0.5282 - val_loss: 0.7187 - val_accuracy: 0.6667
Epoch 7/10
5/5 [==============================] - 0s 15ms/step - loss: 0.8148 - accuracy: 0.5423 - val_loss: 0.9611 - val_accuracy: 0.5833
Epoch 8/10
5/5 [==========

In [ ]:
hist1 = model2.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
5/5 [==============================] - 1s 62ms/step - loss: 10.4298 - accuracy: 0.3521 - val_loss: 2.1457 - val_accuracy: 0.5556
Epoch 2/10
5/5 [==============================] - 0s 11ms/step - loss: 2.5722 - accuracy: 0.3451 - val_loss: 1.2377 - val_accuracy: 0.6667
Epoch 3/10
5/5 [==============================] - 0s 11ms/step - loss: 1.5602 - accuracy: 0.4507 - val_loss: 2.1838 - val_accuracy: 0.3889
Epoch 4/10
5/5 [==============================] - 0s 12ms/step - loss: 2.1044 - accuracy: 0.4718 - val_loss: 1.4208 - val_accuracy: 0.5556
Epoch 5/10
5/5 [==============================] - 0s 11ms/step - loss: 1.6640 - accuracy: 0.4930 - val_loss: 1.4251 - val_accuracy: 0.6667
Epoch 6/10
5/5 [==============================] - 0s 13ms/step - loss: 1.4785 - accuracy: 0.5000 - val_loss: 1.6531 - val_accuracy: 0.6111
Epoch 7/10
5/5 [==============================] - 0s 11ms/step - loss: 1.8562 - accuracy: 0.6338 - val_loss: 0.9904 - val_accuracy: 0.4722
Epoch 8/10
5/5 [==========

In [ ]:
hist3 = model3.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10


AttributeError: ignored

---

###결과 확인

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
import numpy as np

def tf_model(x):
  y_pred = x.predict(X_test)
  y_test_class = np.argmax(y_test,axis=1)
  y_pred_class = np.argmax(y_pred,axis=1)

  print(classification_report(y_test_class,y_pred_class))

In [ ]:
tf_model(model1)

2/2 [==============================] - 0s 7ms/step
              precision    recall  f1-score   support

           0       1.00      0.67      0.80        12
           1       0.50      1.00      0.67        14
           2       0.00      0.00      0.00        10

    accuracy                           0.61        36
   macro avg       0.50      0.56      0.49        36
weighted avg       0.53      0.61      0.53        36



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
tf_model(model2)

2/2 [==============================] - 0s 10ms/step
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.83      0.36      0.50        14
           2       0.43      0.90      0.58        10

    accuracy                           0.64        36
   macro avg       0.75      0.67      0.65        36
weighted avg       0.78      0.64      0.64        36

