##다양한(iris_model)

이번에는 기본적으로 제공하는 iris 데이터에 다양한 머신러닝 모델과 딥러닝 모델을

비교해보도록 하겠습니다.

머신러닝 모델이 더 좋을까요? 딥러닝 모델이 더 좋을까요?

---

##iris 데이터 로드

In [1]:
import numpy as np
import sklearn
from sklearn.datasets import load_iris

iris = load_iris()

X = iris['data']
y = iris['target']

---

##데이터 확인

데이터를 확인해 본 결과 타겟(y) 값은 0 ~ 2로 나오는 걸 확인하실 수 있습니다.

In [2]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

---

##데이터 분리

모델에 넣어줄 데이터를 분리해줍니다.



```
from sklearn.model_selection import train_test_split
```
train_test_split라는 라이브러리를 이용하면 쉽게 분리하실수 있습니다.

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


---

## 머신러닝 모델 적용 및 결과 확인

model이라는 함수를 만들어서 LogisticRegression, GaussianNB,

DecisionTreeClassifier, SVC 4가지 모델에 대해서 성능을 확인 해보겠습니다.

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix

def model(x = LogisticRegression):
  x = x()
  x.fit(X_train,y_train)
  y_pred = x.predict(X_test)
  print(x, classification_report(y_test,y_pred))

In [6]:
model(LogisticRegression)

LogisticRegression()               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [7]:
model(GaussianNB)

GaussianNB()               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [8]:
model(DecisionTreeClassifier)

DecisionTreeClassifier()               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [9]:
model(SVC)

SVC()               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



---

##Tensorflow

이번에는 딥러닝 기법으로 모델을 만들고 성능을 확인해보겠습니다.

딥러닝 모델을 만들시에는 전처리를 약간은 다르게 해 줄 필요가 있습니다.

In [10]:
import tensorflow as tf
from keras.utils.np_utils import to_categorical

iris_label = to_categorical(iris.target)

X = iris.data
y = iris_label

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42, stratify = y)

---

##Sequential API

In [26]:
from tensorflow import keras
from tensorflow.keras import layers
from keras.optimizers import Adam

model = keras.models.Sequential([
    layers.Dense(512, input_dim = 4, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(3, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_42 (Dense)            (None, 512)               2560      
                                                                 
 dense_43 (Dense)            (None, 256)               131328    
                                                                 
 dense_44 (Dense)            (None, 128)               32896     
                                                                 
 dense_45 (Dense)            (None, 64)                8256      
                                                                 
 dense_46 (Dense)            (None, 32)                2080      
                                                                 
 dense_47 (Dense)            (None, 3)                 99        
                                                                 
Total params: 177,219
Trainable params: 177,219
Non-tr

---

##Functional API

In [23]:
inputs = keras.Input(shape = (4,))
x = layers.Dense(512, activation='relu')(inputs)
x = layers.Dense(256, activation='relu')(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dense(32, activation='relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)

model1 = keras.Model(inputs=inputs, outputs=outputs)

model1.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model1.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_36 (Dense)            (None, 512)               2560      
                                                                 
 dense_37 (Dense)            (None, 256)               131328    
                                                                 
 dense_38 (Dense)            (None, 128)               32896     
                                                                 
 dense_39 (Dense)            (None, 64)                8256      
                                                                 
 dense_40 (Dense)            (None, 32)                2080      
                                                                 
 dense_41 (Dense)            (None, 3)                 99  

---

##Subclassing API

In [20]:
class model(tf.keras.Model):
  def __init__(self):
    super(model, self).__init__()
    self.dense1 = layers.Dense(512, activation='relu')
    self.dense2 = layers.Dense(256, activation='relu')
    self.dense3 = layers.Dense(128, activation='relu')
    self.dense4 = layers.Dense(64, activation='relu')
    self.dense5 = layers.Dense(32, activation='relu')
    self.dense6 = layers.Dense(3, activation='softmax')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    x = self.dense3(x)
    x = self.dense4(x)
    x = self.dense5(x)
    x = self.dense6(x)
    return x

model2 = model()
model2.build(input_shape=(1,4))

In [21]:
model2.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])
model2.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_30 (Dense)            multiple                  2560      
                                                                 
 dense_31 (Dense)            multiple                  131328    
                                                                 
 dense_32 (Dense)            multiple                  32896     
                                                                 
 dense_33 (Dense)            multiple                  8256      
                                                                 
 dense_34 (Dense)            multiple                  2080      
                                                                 
 dense_35 (Dense)            multiple                  99        
                                                                 
Total params: 177,219
Trainable params: 177,219
Non-trainab

---

## model_train

In [27]:
hist = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 52ms/step - loss: 1.0538 - accuracy: 0.6000 - val_loss: 0.8997 - val_accuracy: 0.6333
Epoch 2/10
4/4 [==============================] - 0s 10ms/step - loss: 0.8600 - accuracy: 0.6417 - val_loss: 0.7020 - val_accuracy: 0.8333
Epoch 3/10
4/4 [==============================] - 0s 9ms/step - loss: 0.6493 - accuracy: 0.8833 - val_loss: 0.5297 - val_accuracy: 0.9667
Epoch 4/10
4/4 [==============================] - 0s 10ms/step - loss: 0.4845 - accuracy: 0.9250 - val_loss: 0.4038 - val_accuracy: 0.8667
Epoch 5/10
4/4 [==============================] - 0s 9ms/step - loss: 0.3830 - accuracy: 0.8917 - val_loss: 0.3140 - val_accuracy: 0.9667
Epoch 6/10
4/4 [==============================] - 0s 10ms/step - loss: 0.3025 - accuracy: 0.9750 - val_loss: 0.2371 - val_accuracy: 1.0000
Epoch 7/10
4/4 [==============================] - 0s 9ms/step - loss: 0.2497 - accuracy: 0.9667 - val_loss: 0.1795 - val_accuracy: 1.0000
Epoch 8/10
4/4 [==============

In [24]:
hist1 = model1.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 52ms/step - loss: 1.0866 - accuracy: 0.4917 - val_loss: 0.9724 - val_accuracy: 0.8333
Epoch 2/10
4/4 [==============================] - 0s 11ms/step - loss: 0.9356 - accuracy: 0.7167 - val_loss: 0.8182 - val_accuracy: 0.8333
Epoch 3/10
4/4 [==============================] - 0s 9ms/step - loss: 0.7585 - accuracy: 0.8250 - val_loss: 0.6514 - val_accuracy: 0.9667
Epoch 4/10
4/4 [==============================] - 0s 11ms/step - loss: 0.6090 - accuracy: 0.9000 - val_loss: 0.5014 - val_accuracy: 0.9000
Epoch 5/10
4/4 [==============================] - 0s 9ms/step - loss: 0.4574 - accuracy: 0.9417 - val_loss: 0.3766 - val_accuracy: 0.9333
Epoch 6/10
4/4 [==============================] - 0s 10ms/step - loss: 0.3532 - accuracy: 0.9667 - val_loss: 0.2855 - val_accuracy: 0.9333
Epoch 7/10
4/4 [==============================] - 0s 12ms/step - loss: 0.2787 - accuracy: 0.9500 - val_loss: 0.2085 - val_accuracy: 0.9667
Epoch 8/10
4/4 [=============

In [28]:
hist2 = model2.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10)

Epoch 1/10
4/4 [==============================] - 1s 54ms/step - loss: 1.0372 - accuracy: 0.4917 - val_loss: 0.9245 - val_accuracy: 0.6667
Epoch 2/10
4/4 [==============================] - 0s 11ms/step - loss: 0.8816 - accuracy: 0.6667 - val_loss: 0.7894 - val_accuracy: 0.6667
Epoch 3/10
4/4 [==============================] - 0s 9ms/step - loss: 0.7440 - accuracy: 0.6667 - val_loss: 0.6450 - val_accuracy: 0.6667
Epoch 4/10
4/4 [==============================] - 0s 9ms/step - loss: 0.6055 - accuracy: 0.7167 - val_loss: 0.5066 - val_accuracy: 0.7000
Epoch 5/10
4/4 [==============================] - 0s 9ms/step - loss: 0.4703 - accuracy: 0.7583 - val_loss: 0.3775 - val_accuracy: 0.9667
Epoch 6/10
4/4 [==============================] - 0s 9ms/step - loss: 0.3593 - accuracy: 0.9167 - val_loss: 0.2855 - val_accuracy: 0.9667
Epoch 7/10
4/4 [==============================] - 0s 9ms/step - loss: 0.2781 - accuracy: 0.9750 - val_loss: 0.2188 - val_accuracy: 0.9333
Epoch 8/10
4/4 [================

---

##model_result

음.. 크게 눈에 뛰는 차이는 보이는거 같지 않습니다.

역시 상황에 따라서 다양하게 쓰는 방법이 필요할꺼 같습니다.



In [29]:
def tf_model(x):
  y_pred = x.predict(X_test)
  y_test_class = np.argmax(y_test,axis=1)
  y_pred_class = np.argmax(y_pred,axis=1)

  print(classification_report(y_test_class,y_pred_class))

In [30]:
tf_model(model)

1/1 [==============================] - 0s 188ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [31]:
tf_model(model1)

1/1 [==============================] - 0s 53ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.80      0.89        10
           2       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [32]:
tf_model(model2)

1/1 [==============================] - 0s 56ms/step
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.70      0.82        10
           2       0.77      1.00      0.87        10

    accuracy                           0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.92      0.90      0.90        30

